title: Add wrapped tiles with text, image, text
hero_image: images/banner.png
description: Add wrapped tiles with text, image, text.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Add wrapped tiles with text, image, text
