---
title: Ajouter des tuiles enveloppées avec du texte, de l'image, du texte
hero_image: images/banner.png
description: Ajoute des tuiles enveloppées avec du texte, de l'image, du texte.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ajouter des tuiles enveloppées avec du texte, de l'image, du texte
